### PR TITLE
Next

### PR DESCRIPTION
**Pull request by adnan1naeem**

### CODE REVIEW

**Comment by adnan1naeem** [comment]
@artalat  it has huge change can u please explain  what is change in this feature  branch

**Comment by artalat** [comment]
the is the latest code of the plugin, that is currently being used in different apps.

**Comment by artalat** [comment]
@adnan1naeem can we close this?

**Comment by artalat** [comment]
@ammarkhan967 @adnan1naeem do we still need this>?

**Comment by adnan1naeem** [comment]
@artalat  we dont need this as code is already in master and working fine

**Pull request closed without merging**
